####################
# -- service binds
####################

# ------------------
# yanic
# ------------------

[yanic-serve]
karte.freifunk-lippe.de

# ------------------
# respondd
# ------------------

[yanic-respondd:children]
freifunk-lippe

[yanic-respondd]
vpn06.bremen.freifunk.net



####################
# -- community binds
####################

# ------------------
# lippe
# ------------------

[freifunk-lippe]
karte.freifunk-lippe.de
gw01.freifunk-lippe.de
gw02.freifunk-lippe.de
gw03.freifunk-lippe.de
gw04.freifunk-lippe.de

# ------------------
# bremen
# ------------------

[freifunk-bremen]
vpn06.bremen.freifunk.net
